import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { generateLevel } from '../src/game/domain/generator';

const LEVEL_COUNT = 100;
const OUT = resolve(process.cwd(), 'src/game/domain/levels.generated.ts');

const levels = Array.from({ length: LEVEL_COUNT }, (_, i) => generateLevel(i + 1));

const body = `// AUTO-GENERATED by scripts/generate-levels.ts. Do not edit by hand.
// Regenerate via: npm run generate-levels
import type { Level } from './types';

export const LEVELS: readonly Level[] = ${JSON.stringify(levels, null, 2)} as const;
`;

writeFileSync(OUT, body);
console.log(`Wrote ${LEVEL_COUNT} levels to ${OUT}`);
